name: OPENML29  
environment:
    image:
        gpu: docker.io/junhongshen/nb360:updatenew
hyperparameters:
    dataset: OPENML29
    embedder_dataset: text
    objective: otdd-exact
    weight: roberta
    maxsamples: 128 
    
    experiment_id: 0
    seed: 0
    epochs: 12
    embedder_epochs: 20
    predictor_epochs: 0
    finetune_method: all
    target_seq_len: 4

    drop_out: 0.05
    batch_size: 64 
    eval_batch_size: 1000
    accum: 1
    clip: 1 
    validation_freq: 1

    optimizer:
        name: AdamW  
        params:
            lr: 0.00001  
            betas: [0.9, 0.98]
            weight_decay: 0.00001  
            momentum: 0.999  

    scheduler:  
        name: WarmupLR 
        params:
            warmup_epochs: 5
            decay_epochs: 60
            sched: [30, 60, 90]
            base: 0.2

    no_warmup_scheduler:  
        name: StepLR
        params:
            warmup_epochs: 10
            decay_epochs: 100
            sched: [20, 40, 60]
            base: 0.2

    num_workers: 4
    reproducibility: False
    valid_split: False

min_validation_period:
    epochs: 1
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
    slots_per_trial: 1
records_per_epoch: 1562
searcher:
    name: single
    metric: "val score"
    smaller_is_better: true
    max_length:
        epochs: 1
max_restarts: 0
entrypoint: python3 main.py